columns:
  age: int64 
  workclass: object
  fnlwgt: int64
  education: object 
  education-num: int64 
  marital-status: object
  occupation: object
  relationship: object
  race: object
  sex: object
  capital-gain: int64 
  capital-loss: int64 
  hours-per-week: int64 
  native-country: object
  income: object


categorical_columns:
- workclass
- marital-status
- occupation
- relationship
- native-country
- race
- sex


numerical_columns:
- age
- fnlwgt
- education-num
- capital-gain
- capital-loss
- hours-per-week


target_column: income

domain_value:
  marital-status:
    - Never-married
    - Married-civ-spouse
    - Divorced
    - Married-spouse-absent
    - Separated
    - Married-AF-spouse
    - Widowed

  sex:
    - Male
    - Female